CREATE TABLE IF NOT EXISTS orders (
    nb_commande INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pain BOOL NOT NULL,
    salade BOOL NOT NULL,
    viande BOOL NOT NULL,
    tomates BOOL NOT NULL
);
