CREATE TABLE IF NOT EXISTS orders (
    nb_commande INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pain BOOL NOT NULL,
    salade BOOL NOT NULL,
    viande BOOL NOT NULL,
    tomates BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS stocks (
    nom_ingredient TEXT PRIMARY KEY ,
    quantite INTEGER NOT NULL,
    prix FLOAT NOT NULL 
);

INSERT INTO stocks VALUES ("viande", 10, 12.89);
